env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true

plugins:
  - eslint-plugin-babel
  - react
  - react-hooks
  - import
  - jsx-a11y

parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true

extends:
  - 'airbnb'
  - 'airbnb/hooks'
  - 'plugin:jsx-a11y/recommended'
  - "plugin:react/recommended"

rules:
  no-console: 0
  indent:
    - error
    - 2
    - SwitchCase: 1
#  react/jsx-indent: [2, 4]
#  react/jsx-indent-props: [2, 4]
  import/no-unresolved: 0
  import/extensions: 0
  react/jsx-props-no-spreading: 0
